### ISSUE TITLE
5.2.1 makes HA to huge time to startup.... only to create Geen

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#123]
## Version of the custom_component

5.2.1
## Configuration

```yaml

Add your logs here.

```

## Describe the bug

After updating to the 5.2.1 version HA took an enormous time to startup and, more importantly, makes all sensors show state 'Geen'

<img width="407" alt="Schermafbeelding 2020-12-09 om 11 29 38" src="https://user-images.githubusercontent.com/33354141/101618137-d8239e00-3a11-11eb-8214-ce43bb50ba30.png">

## Debug log

```text

Add your logs here.
2020-12-09 11:18:03 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalwijzer_gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_provider.py", line 95, in async_update
    waste_data_provider[self.waste_type].date(),
AttributeError: 'datetime.date' object has no attribute 'date'
2020-12-09 11:18:03 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalwijzer_plastic fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_provider.py", line 95, in async_update
    waste_data_provider[self.waste_type].date(),
AttributeError: 'datetime.date' object has no attribute 'date'
2020-12-09 11:18:03 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalwijzer_restafval fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_provider.py", line 95, in async_update
    waste_data_provider[self.waste_type].date(),
AttributeError: 'datetime.date' object has no attribute 'date'
2020-12-09 11:18:03 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalwijzer_next_date fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_custom.py", line 82, in async_update
    waste_data_custom[self.waste_type].date(),
AttributeError: 'datetime.date' object has no attribute 'date'
```

**Comment by Mariusthvdb** [comment]
....seeing 3 new version have arrived in the past 10 minutes....

haha, we were too quick to update.
have a go at 5.2.4 and will report back if necessary.

**Comment by xirixiz** [comment]
...yeah, just thought doing some ninja updates without testing, that's not good hahaha

**Comment by xirixiz** [comment]
5.2.6 now ...

**Comment by Mariusthvdb** [comment]
still not as it should be:

<img width="868" alt="Schermafbeelding 2020-12-09 om 12 02 06" src="https://user-images.githubusercontent.com/33354141/101621745-7285e080-3a16-11eb-9ba3-888f8a6a32ab.png">

is_collection_date_today: false should be true.

also, instead of showing the last correct date on several sensors, we now have `null`, is that what you want?

**Comment by xirixiz** [comment]
is_collection_date_today: false is correct as there the state is Geen, so it's not going to be picked up Today.

The other values being null is also correct, but I could make it Geen (default_label) as well.

**Comment by Mariusthvdb** [comment]
no, Papier is picked up today. It shouldn't be 'Geen'? days_until_collection_date is null, which is correct, as it isnt set by the Saver yet for 2021.

as for the null, I've translated the template to use that 'is none', which make it a bit shorter, and more concise, so that's good:

```
      include:
        - entity_id: sensor.afvalwijzer_*
          options:
            type: custom:template-entity-row
            state: >
              {% set trash = config.entity %}
              {% set future = state_attr(trash,'days_until_collection_date') %}
              {% if future is none %} Tba
              {% else %}
              {{as_timestamp(strptime(states(trash),'%d-%m-%Y'))
                              |timestamp_custom('%-d %b')}}
              {% endif %}
            secondary: >
              {% set trash = config.entity %}
              {% set future = state_attr(trash,'days_until_collection_date') %}
              {% if future is none %} Nog niet gepubliceerd
              {% else %}
                {% set count = state_attr(trash,'days_until_collection_date')|int %}
                {% set day = as_timestamp(strptime(states(trash),'%d-%m-%Y'))
                   |timestamp_custom('%A') %}
                {% set dagen =
                  {'Monday': 'Maandag',
                  'Tuesday': 'Dinsdag',
                  'Wednesday': 'Woensdag',
                  'Thursday': 'Donderdag',
                  'Friday': 'Vrijdag',
                  'Saturday': 'Zaterdag',
                  'Sunday': 'Zondag'} %}
                {% set dag = dagen[day] if day in dagen else day %}
                {% set unit = 'Dag' if count == 1 else 'dagen' %}

                {% if count >= 14 %} {% set phrase = dag + ' over 2 weken' %}
                {% elif count >= 7 %} {% set phrase = 'Volgende week ' + dag %}
                {% elif count >= 3 %} {% set phrase = 'komende ' + dag %}
                {% elif count == 2 %} {% set phrase = dag + ', overmorgen' %}
                {% elif count == 1 %} {% set phrase = 'morgen, ' + dag %}
                {% else %} {% set phrase = 'Vandaag, ' + dag %}
                {% endif %}
                {{phrase}} {% if count != 0 %} ({{count}} {{unit}}) {% endif %}
              {% endif %}
```

I think it would be preferable too only use 'Geen' if the integration has a positive on that, meaning it has truly been able to see there is no Pickup for that trash.

If it cant determine that, it should keep the null imho.

Also makes templating easier

**Comment by xirixiz** [comment]
Weird, in debug it says:
Generating state via AfvalwijzerCustomSensor for = today with value papier

**Comment by xirixiz** [comment]
For now I did a rollback of all changes Today. I will fix/change some things when I have more time, maybe this weekend :)
