### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by tabnul** [xirixiz/homeassistant-afvalwijzer#125]
After updating to 5.2.6 (coming from 5.2.1) i get the following error (plugin stopped working);

```

2020-12-10 14:31:18 | File "/config/custom_components/afvalwijzer/provider/afvalwijzer.py", line 60, in __init__
2020-12-10 14:31:18 | result = self.fn(*self.args, **self.kwargs)
2020-12-10 14:31:18 | File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2020-12-10 14:31:18 | afvalwijzer = await hass.async_add_executor_job(
2020-12-10 14:31:18 | File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
2020-12-10 14:31:18 | await asyncio.shield(task)
2020-12-10 14:31:18 | File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
2020-12-10 14:31:18 | Traceback (most recent call last):
2020-12-10 14:31:18 | 2020-12-10 13:31:18 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
2020-12-10 14:31:18 | 2020-12-10 13:31:18 ERROR (SyncWorker_2) [custom_components.afvalwijzer.const.const] Other error occurred: 'ophaaldagen'

```

**Comment by xirixiz** [comment]
Can you provide your postal code and random street-/housenumber so I can reproduce the issue? You can also PM me atthe hass community.

**Comment by xirixiz** [comment]
True, you need to upgrade to 5.2.7 👍

I just checked and data is being retrieved properly using 5.2.7.

```
{'restafval': datetime.datetime(2020, 12, 10, 0, 0), 'pmd': datetime.datetime(2020, 12, 17, 0, 0), 'gft': datetime.datetime(2020, 12, 21, 0, 0), 'papier': datetime.datetime(2020, 12, 29, 0, 0)}
{'pmd': datetime.datetime(2020, 12, 17, 0, 0), 'gft': datetime.datetime(2020, 12, 21, 0, 0), 'papier': datetime.datetime(2020, 12, 29, 0, 0), 'restafval': 'Geen'}
{'today': 'restafval', 'tomorrow': 'Geen', 'day_after_tomorrow': 'Geen', 'next_date': datetime.datetime(2020, 12, 17, 0, 0), 'next_in_days': 7, 'next_item': 'pmd'}
['pmd', 'gft', 'papier', 'restafval']
['today', 'tomorrow', 'day_after_tomorrow', 'next_date', 'next_in_days', 'next_item']
```

**Comment by tabnul** [comment]
sorry, i am actually allready at 5.2.7 (mistyped the version number)

**Comment by xirixiz** [comment]
Please try 5.2.8, I noticed the suffix was interpreted incorrectly.

**Comment by tabnul** [comment]
That was it, thanks for the fast support!
