### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by yfands** [xirixiz/homeassistant-afvalwijzer#156]
### Issue

Hello, iam getting a index out of range, guess its related to the new year...
I dont think its an program error, the information for the new year isnt available yet..
So a 'not available yet' would do the trick.

iam using https://www.mijnafvalwijzer.nl

Regards Frank

### Which version has the issue?

core-2021.12.5

### What was the last working version?

No idea havent had a change of year yet

### Anything in the logs that might be useful?

```txt
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:292
Integration: afvalwijzer (documentation, issues)
First occurred: 00:28:23 (10 occurrences)
Last logged: 09:32:54

Error occurred: list index out of range


Related error:

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.helpers.entity
Source: custom_components/afvalwijzer/sensor_custom.py:88
Integration: afvalwijzer (documentation, issues)
First occurred: 00:31:52 (33 occurrences)
Last logged: 10:32:54

Update for sensor.afvalwijzer_next_item fails
Update for sensor.afvalwijzer_next_date fails
Update for sensor.afvalwijzer_next_in_days fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_custom.py", line 88, in async_update
    if isinstance(waste_data_custom[self.waste_type], datetime):
KeyError: 'next_item'
```

**Comment by yfands** [comment]
Update, the error is gone the next year is available on mijnafvalwijzer, so the 'program' is whole again till the end of next year ;-)

**Comment by xirixiz** [comment]
Hi, yes, working on it :)
