### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by droeloe1818** [xirixiz/homeassistant-afvalwijzer#165]
### Issue

Hello,

I installed the addon and put the information in the config file.

Now i get an error.

I saw on threads that more people have this problem.

### Which version has the issue?

Latest

### What was the last working version?

idk

### Anything in the logs that might be useful?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 67, in async_setup_platform
    afvalwijzer = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/provider/afvalwijzer.py", line 70, in __init__
    (
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by xirixiz** [comment]
What is your postal code?

**Comment by xirixiz** [comment]
No reply, closing.
