### ISSUE TITLE
Sensors not created

### ISSUE THREAD

**Issue by Wolk9** [xirixiz/homeassistant-afvalwijzer#175]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Despite following the described installation/setup I don't see created sensors, but get an error in my logs. 

``` Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/mijnafvalwijzer.py:76
Integration: Sensor (documentation, issues)
First occurred: 16:13:27 (1 occurrences)
Last logged: 16:13:27

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 69, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 47, in __init__
    ) = self.get_waste_data_provider()
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 76, in get_waste_data_provider
    json_response["ophaaldagen"]["data"]
KeyError: 'ophaaldagen'
```

### Expected behaviour

I expected to see my declared sensors in the list of entities.

### Actual behaviour

There are no sensors created.

I can't find/see the sensors in my developer tools either. 

### Version

* HASS version: 2022.2.9
* Component version: 2022.02.01
* Useful system info: RPi4 

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml
``` Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/mijnafvalwijzer.py:76
Integration: Sensor (documentation, issues)
First occurred: 16:13:27 (1 occurrences)
Last logged: 16:13:27

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 69, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 47, in __init__
    ) = self.get_waste_data_provider()
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 76, in get_waste_data_provider
    json_response["ophaaldagen"]["data"]
KeyError: 'ophaaldagen'
```

**Comment by xirixiz** [comment]
Hi, what is your postal code?

**Comment by RemcoVisser1978** [comment]
Please help me to get 'afvalwijzer' to work again, I can't even restart my server.

due to the following error:


Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:609
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:05:18 (7 occurrences)
Last logged: 10:09:31

[547304961936] The system cannot restart because the configuration is not valid: Platform error sensor.afvalwijzer - Integration 'afvalwijzer' not found.
[547324087312] The system cannot restart because the configuration is not valid: Platform error sensor.afvalwijzer - Integration 'afvalwijzer' not found.
[547246315792] The system cannot restart because the configuration is not valid: Platform error sensor.afvalwijzer - Integration 'afvalwijzer' not found.
[547298977104] The system cannot restart because the configuration is not valid: Platform error sensor.afvalwijzer - Integration 'afvalwijzer' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 609, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.afvalwijzer - Integration 'afvalwijzer' not found.

**Comment by xirixiz** [comment]
It seems that afvalwijzer is missing completely. Please verify your custom_components folder here: ```/config/custom_components/```

The folder afvalwijzer and subfolders should exist on that location.

**Comment by RemcoVisser1978** [comment]
Hi xirixiz,

thanks for the quick reply. The /config/custom_components/ folder did exist on my system. To be shure i deleted the folder and the afvalwijzer config. After reinstalling and restart the server everything works as it did before.
