### ISSUE TITLE
After Update to Home Assistant 2022.4.5 - Other error occurred: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by D-on-GitHub** [xirixiz/homeassistant-afvalwijzer#184]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

After upgrading to Home Assistant 2022.4.5, the Afvalwijzer integration will not load.

### Expected behaviour

The integration would load and would populate the entities with the correct info.

### Actual behaviour

The entities are not populated, the log gives the following error:

Logger: homeassistant.components.sensor
Source: /usr/local/lib/python3.9/asyncio/events.py:80 
Integration: Sensor (documentation, issues) 
First occurred: 20:01:44 (1 occurrences) 
Last logged: 20:01:44

Setup of sensor platform afvalwijzer is taking over 10 seconds.

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/collector/ximmio.py:155 
Integration: afvalwijzer (documentation, issues) 
First occurred: 20:01:48 (1 occurrences) 
Last logged: 20:01:48

Other error occurred: 'NoneType' object is not iterable

Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/ximmio.py:45 
Integration: Sensor (documentation, issues) 
First occurred: 20:01:48 (1 occurrences) 
Last logged: 20:01:48

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 97, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 45, in __init__
    (
TypeError: cannot unpack non-iterable NoneType object

### Version

* HASS version: 2022.4.5
* Component version: 2022.02.03
* Useful system info: running Home Assistant OS, all-up-to-date. API: rein's

### HASS logs

Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/ximmio.py:45 
Integration: Sensor (documentation, issues) 
First occurred: 20:01:48 (1 occurrences) 
Last logged: 20:01:48

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 97, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 45, in __init__
    (
TypeError: cannot unpack non-iterable NoneType object

**Comment by xirixiz** [comment]
Hi, can you share your postal code so I can perform some test?

**Comment by evanlaar01** [comment]
Same issue:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 97, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 49, in __init__
    ) = self.get_waste_data_provider()
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 73, in get_waste_data_provider
    uniqueId = raw_response.json()["dataList"][0]["UniqueId"]
TypeError: 'NoneType' object is not subscriptable
```
Postal code 
6713CG 
House numbers are many available, for example 11

**Comment by xirixiz** [comment]
Thanks! I`ll validate some things.

**Comment by xirixiz** [comment]
Hi, for me it's working fine (either via Python itself or via HASS). Not sure what is happening, but could you restart HASS and verify again? Maybe reinstall the component via HACS (I just did that ass wel, but also no issues then)?

Debug output:
```
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating waste_types_provider list = ['gft', 'papier', 'pmd']
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating waste_types_custom list = ['day_after_tomorrow', 'next_date', 'next_in_days', 'nex
t_type', 'today', 'tomorrow']
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor provider: gft
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor provider: papier
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor provider: pmd
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor custom: day_after_tomorrow
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor custom: next_date
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor custom: next_in_days
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor custom: next_type
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor custom: today
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Adding sensor custom: tomorrow
2022-04-20 11:57:38 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Entities appended = [<Entity afvalwijzer gft: Geen>, <Entity afvalwijzer papier: Geen>, <Enti
ty afvalwijzer pmd: Geen>, <Entity afvalwijzer day_after_tomorrow: Geen>, <Entity afvalwijzer next_date: Geen>, <Entity afvalwijzer next_in_days: Geen>, <Entity afvalwijzer nex
t_type: Geen>, <Entity afvalwijzer today: Geen>, <Entity afvalwijzer tomorrow: Geen>]
```

**Comment by xirixiz** [comment]
Yeah, most propbably there was an issue at the provider site which seems to be resolved now :).

**Comment by xirixiz** [comment]
Just drafted a new release as I noticed an unwanted print in the logfiles for ximmio 😄
