### ISSUE TITLE
If afvalwijzer is not reachable sensor stays Unavailable until HA restart

### ISSUE THREAD

**Issue by rotilho** [xirixiz/homeassistant-afvalwijzer#195]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Afvalwijzer never recovers if afvalwijzer is not reachable. The only way to fix it is restarting the HA

### Expected behaviour

Afvalwijzer retries after some time

### Actual behaviour

Afvalwijzer stays unavailable

### Version

* HASS version: 2022.7.1
* Component version: 2022.06.02
* Useful system info:

### HASS logs

```
[31m2022-07-10 11:03:15 ERROR (MainThread) [custom_components.afvalwijzer.const.const] Check afvalwijzer platform settings (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.mijnafvalwijzer.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=1234KM&street=&huisnummer=888&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2022-07-10&langs=nl& (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffab1ccdf0>: Failed to establish a new connection: [Errno -3] Try again'))")),)[0m
[31m2022-07-10 11:03:16 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/afvalwijzer/sensor.py", line 130, in async_setup_platform
if collector == "":
UnboundLocalError: local variable 'collector' referenced before assignment[0m
```

**Comment by xirixiz** [comment]
Hi, do you still have this issue?
