### ISSUE TITLE
No afvalwijzer dates for 2023 (yet)

### ISSUE THREAD

**Issue by ceesvanegmond** [xirixiz/homeassistant-afvalwijzer#211]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

First of all; I love this integration. It helped my plenty of times last year.
But for this year; it appears that there's no data in mijnafvalwijzer.nl. Maybe my town switched providers?

### Expected behaviour

That the dates of 2023 are there.

### Actual behaviour

As you can see in the logs is the URL the integration if fetching is returning nothing but NO OK; which implies that my town haven't updated the dates yet? But when I login the the prezero website the calendar is definately there. Any idea?

### Version

Not relevant

### HASS logs

Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/mijnafvalwijzer.py:52
Integration: Sensor (documentation, issues)
First occurred: 1:12:38 PM (1 occurrences)
Last logged: 1:12:38 PM

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 49, in get_waste_data_raw
    response["ophaaldagen"]["data"] + response["ophaaldagenNext"]["data"]
KeyError: 'ophaaldagen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 39, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 52, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from exc
KeyError: 'Invalid and/or no data received from https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=2172VJ&street=&huisnummer=10&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-01-02&langs=nl&'

**Comment by xirixiz** [comment]
When I use the frontend of mijnafvalwijzer for your address.... it seems indeed the case that your town isn't supported by mijnafvalwijzer anymore:

![image](https://user-images.githubusercontent.com/11210639/210234413-6f1d3e33-5948-44f8-84dc-8cd8fbc2d138.png)

Luckily for you, I also support prezero ;)

**Comment by ceesvanegmond** [comment]
@xirixiz Yes but can I force `prezero`? And how do I do that?

**Comment by xirixiz** [comment]
Np, you're welcome

**Comment by wtrdk** [comment]
I have the same problem, using RMN as provider. The RMN app on my iPhone still works, but the integration gives this error:

`Other error occurred _get_next_waste_in_days: unsupported operand type(s) for -: 'datetime.datetime' and 'str'`
