### ISSUE TITLE
Update for calendar.afval fails (HASS 2023.4)

### ISSUE THREAD

**Issue by haaino** [xirixiz/homeassistant-afvalwijzer#233]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Since HASS 2023.4 I get error messages in the frontend and in the logfile

### Expected behaviour

No error messages in calendar

### Actual behaviour

Error messages in the calendar. (Could not retrieve events for calendars: Afval)

### Version

HASS 2023.4

### HASS logs

 Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:345
First occurred: 5 April 2023 at 22:18:09 (652 occurrences)
Last logged: 09:09:11
Update for calendar.afval fails

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 270, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00

**Comment by AppleFlapp** [comment]
I don't have logs available anymore but I think I had similar problem.
My card was not showing any info. Clicking an item on the card told me the entity was not available.
Looking a bit further I found something that the integration was not providing the entities.
Entities could not be restored. 

I did remove the integration (and all items relating to it in the config files) and re-install but without succes.
Might give it another attempt tomorrow.

**Comment by xirixiz** [comment]
Can you share your postal code?

**Comment by AppleFlapp** [comment]
Sure.

provider: afvalstoffendienstkalender
zipcode: 4266NB

A colleague of mine also has issues. He lives in Rosmalen but with the same provider though.

**Comment by platte-73** [comment]
Here the same. all entities are unavailable

**Comment by xirixiz** [comment]
Working on it 👍🏻

**Comment by xirixiz** [comment]
afvalstoffendienstkalender fixed in release: 2023.04.01

**Comment by haaino** [comment]
Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:345 
First occurred: 15:00:04 (2 occurrences) 
Last logged: 15:01:04

Update for calendar.afval fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 270, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

**Comment by xirixiz** [comment]
@AppleFlapp Goed om te horen, wel waardeloos van de provider.... het certificaat van de url is al maanden niet meer geldig.

**Comment by xirixiz** [comment]
@haaino Werkt als een zonnetje!

```
{'milieustraat_gesloten': datetime.datetime(2023, 4, 10, 0, 0), 'restafval': datetime.datetime(2023, 4, 13, 0, 0), 'gft': datetime.datetime(2023, 4, 17, 0, 0), 'pmd': datetime.datetime(2023, 4, 20, 0, 0), 'papier': datetime.datetime(2023, 4, 22, 0, 0), 'takken': datetime.datetime(2023, 5, 5, 0, 0), 'kca': datetime.datetime(2023, 9, 2, 0, 0), 'textiel': datetime.datetime(2023, 11, 1, 0, 0)}
{'restafval': datetime.datetime(2023, 4, 13, 0, 0), 'gft': datetime.datetime(2023, 4, 17, 0, 0), 'pmd': datetime.datetime(2023, 4, 20, 0, 0), 'papier': datetime.datetime(2023, 4, 22, 0, 0), 'milieustraat_gesloten': datetime.datetime(2023, 4, 27, 0, 0), 'takken': datetime.datetime(2023, 5, 5, 0, 0), 'kca': datetime.datetime(2023, 9, 2, 0, 0), 'textiel': datetime.datetime(2023, 11, 1, 0, 0)}
{'next_date': datetime.datetime(2023, 4, 13, 0, 0), 'next_in_days': 3, 'next_type': 'restafval', 'today': 'milieustraat_gesloten', 'tomorrow': 'geen', 'day_after_tomorrow': 'geen'}
['gft', 'kca', 'milieustraat_gesloten', 'papier', 'pmd', 'restafval', 'takken', 'textiel']
['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']
```

Heb je het als volgt gedefinieerd:
```
provider = "mijnafvalwijzer"
postal_code = "<postcode>"
street_number = "<huisnummer"
```

**Comment by AppleFlapp** [comment]
> @AppleFlapp Goed om te horen, wel waardeloos van de provider.... het certificaat van de url is al maanden niet meer geldig.

Dat is wel slordig ja.

**Comment by haaino** [comment]
Fijn om te weten dat de plek van de issue is gelokaliseerd. 

Had er inderdaad geen quote omheen gezet. Heb dat nu wel gedaan. 

Gedrag veranderd helaas niet. 

Issue openen op een andere plek?

**Comment by xirixiz** [comment]
@haaino Het ligt eraan wat er precies mis gaat. Het ligt iig niet bij dit component.

Wanneer je naar Deveoper Tools en dan States gaat, en dan zoekt op afvalwijzer, dan moeten alle sensoren voor dit component daar zichtbaar zijn. Zoiets als dit:

![image](https://user-images.githubusercontent.com/11210639/230909369-51992fb0-2993-4bd4-a405-3ab21baa5fd0.png)

Ik weet niet precies wat je probeert te doen met een ander component, maar daarbij is iig iets niet goed geconfigureerd. Ik zou beginnen bij een ticket te openen bij "entites_calendar", ik denk calendar card dat de intergratie heet.
