### ISSUE TITLE
Update on 233

### ISSUE THREAD

**Issue by haaino** [xirixiz/homeassistant-afvalwijzer#234]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:345 
First occurred: 15:00:04 (2 occurrences) 
Last logged: 15:01:04

Update for calendar.afval fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 178, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/entities_calendar/calendar.py", line 270, in update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-04-17 02:00:00+02:00, 2023-04-17 02:00:00+02:00)

### Expected behaviour

Postcode 3951 eb

Mijnafvalwijzer

### Actual behaviour

Error 

### Version

* HASS version: 2022.4.1

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by haaino** [comment]
FYI

HA 2023.4.3 resolves this issue.
