### ISSUE TITLE
Afvalwijzer sensors not working after update

### ISSUE THREAD

**Issue by FritsOV** [xirixiz/homeassistant-afvalwijzer#238]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

After updating HAS  sensors does not show any data anymore.
In a separate second HAS setup on an other system it still works.  This setup has an afvalwijzer setup 23.01.01 and HAS version:2023.3.3 

### Expected behaviour

fetching dates for the sensors gft,pmd and trash 

### Actual behaviour

sensor.afvalwijzer_day_after_tomorrow      | unavailable | 
sensor.afvalwijzer_days_until_collection_date      | 100 | 
sensor.afvalwijzer_first_next_item_formatted      |   | 
sensor.afvalwijzer_gft                 | unavailable | 
sensor.afvalwijzer_next_date      | unavailable | 
sensor.afvalwijzer_next_in_days   | unavailable | 
sensor.afvalwijzer_next_type      | unavailable | 
sensor.afvalwijzer_pmd     | unavailable | 
sensor.afvalwijzer_restafval    | unavailable | 
sensor.afvalwijzer_today      | unavailable | 
sensor.afvalwijzer_today_formatted     | Geen | 
sensor.afvalwijzer_tomorrow     | unavailable | 
sensor.afvalwijzer_tomorrow_formatted      | Geen | 
etcetera........

### Version

 
 Home Assistant 2023.5.2 Supervisor 2023.04.1 Operating System 10.1 Frontend-versie: 20230411.1 - latest 
afvalwijzer version 2023.04.03

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

Error log:
Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/main_collector.py:99
Integration: Sensor (documentation, issues)
First occurred: 7 mei 2023 om 20:43:03 (1 occurrences)
Last logged: 7 mei 2023 om 20:43:03

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 99, in __init__
    waste_data_raw,
UnboundLocalError: local variable 'waste_data_raw' referenced before assignment

And:

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/collector/main_collector.py:93
Integration: afvalwijzer (documentation, issues)
First occurred: 7 mei 2023 om 20:43:03 (1 occurrences)
Last logged: 7 mei 2023 om 20:43:03

Check afvalwijzer platform settings (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.inzamelkalender.rova.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=XXXXXXXX&street=&huisnummer=XX&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-05-07&langs=nl& (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde2123b700>: Failed to establish a new connection: [Errno -3] Try again'))")),)

**Comment by FritsOV** [comment]
Solved the problem all working fine now.
