### ISSUE TITLE
Suddenly Afvalwijzer not working anymore.

### ISSUE THREAD

**Issue by BobPuts** [xirixiz/homeassistant-afvalwijzer#254]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

After changing Network docker container to Host and back to Bridge i noticed that Afvalwijzer is not working anymore. Tried to reinstall but didn't help at all.

### Expected behaviour

working app

### Actual behaviour

not working

### Version

Core
2023.12.0
Frontend
20231206.0

component:  
2023.09.01

### HASS logs

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/collector/main_collector.py:93
Integration: afvalwijzer ([documentation](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md), [issues](https://github.com/xirixiz/homeassistant-afvalwijzer/issues))
First occurred: 22:04:18 (1 occurrences)
Last logged: 22:04:18

Check afvalwijzer platform settings ('Expecting value: line 1 column 1 (char 0)',)

And
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 99, in __init__
    waste_data_raw,
    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'waste_data_raw' where it is not associated with a value

**Comment by vincentnk** [comment]
This integration also suddenly stopped working for me, so maybe the issue is not your docker change.

Since 20h this evening I saw this error in log:

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:359
Integration: Sensor (documentation, issues)
First occurred: 20:17:17 (1 occurrences)
Last logged: 20:17:17

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 41, in get_waste_data_raw
    if not response["ophaaldagen"]:
           ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'ophaaldagen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 40, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 45, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from err
KeyError: 'Invalid and/or no data received from https://api.inzamelkalender.rova.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=******&street=&huisnummer=*&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-12-07&langs=nl&'
`

Could be the inzamelkalender API is having some issues?

**Comment by ictforum-nl** [comment]
Hi, i'm getting an error:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: 7 december 2023 om 21:51:46 (1 occurrences)
Last logged: 7 december 2023 om 21:51:46

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 41, in get_waste_data_raw
    if not response["ophaaldagen"]:
           ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'ophaaldagen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 40, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 45, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from err
KeyError: 'Invalid and/or no data received from https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=1
[api response.txt](https://github.com/xirixiz/homeassistant-afvalwijzer/files/13613204/api.response.txt)
[api response.txt](https://github.com/xirixiz/homeassistant-afvalwijzer/files/13613209/api.response.txt)
234AB&street=&huisnummer=1&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-12-07&langs=nl&'

(i've changed the postcode)

looks like the api is returning something not expected? "ophaaldagen" ?

when i put the api call in my browser i get correct results (attached)

**Comment by damianeickhoff** [comment]
@ictforum-nl I had the same issue. I fixed it by changing the provider in the `configuration.yaml` to the one corresponding for my region. 

Note: For me the API response didn't work neither so I'm not sure if this will fix your issue.

**Comment by ictforum-nl** [comment]
with me it started working again without doing anything

**Comment by xirixiz** [comment]
Yeah, these kind of issues always appear towards the end of the year. Communities update their data and sometimes this process is a bit weird 😂. Anyway, results are errors like this. Let me check if I can make a more userfriendly message out of it.

**Comment by Revaes** [comment]
Same Issue (and error in de logs) here. The API call does actually return a result.

`2023-12-07 20:48:14.797 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration afvalwijzer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-07 20:48:28.875 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 41, in get_waste_data_raw
File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 40, in __init__
waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 45, in get_waste_data_raw
KeyError: 'Invalid and/or no data received fromhttps://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=3721TK&street=&huisnummer=66&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-12-07&langs=nl&'`

**Comment by xirixiz** [comment]
@Revaes it is weird though, as I configure test the component with your postal code and huisnummer, then the component is working just fine. I`ll do some additional testing. Can you restart HASS perhaps to check again?

**Comment by Revaes** [comment]
Just rebooted and it works again!
Weird since i rebooted many times in the last week for other stuff. But happy nevertheless.

**Comment by xirixiz** [comment]
Drafted release: 2023.12.01

Sorry for the delay. Forgot about it due to the holidays :)
