### ISSUE TITLE
Misleading documentation 

### ISSUE THREAD

**Issue by aad4** [xirixiz/homeassistant-afvalwijzer#264]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

The example configuration.yaml  is a bit misleading. It mentions:
 
    provider: mijnafvalwijzer       # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova

It would be clearer if it would refer to the list of collectors (that is shown when clicking on the custom component in HACS) as possible values. Suppose you live in Almere, then the configuration should contain:

    provider: almere

BTW: it is also confusing to use two terms for the same thing (provider and collector).

### Expected behaviour

The component uses the right endpoint to get the data.

### Actual behaviour

I thought I needed to select one of the mentioned three options, so I took mijnafvalwijzer and then for my postal code I got no data back, making the sensor return an error, resulting in no card being shown.

### Version

* HASS version: 2024.1.0
* Component version: 2023.12.02
* Useful system info:

### HASS logs

```
2024-01-04 10:52:22.033 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 41, in get_waste_data_raw
if not response["ophaaldagen"]:
~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'ophaaldagen'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
collector = await hass.async_add_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 40, in __init__
waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 45, in get_waste_data_raw
raise KeyError(f"Invalid and/or no data received from {url}") from err
KeyError: 'Invalid and/or no data received from https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=XXXXXX&street=&huisnummer=XX&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2024-01-04&langs=nl&'
```

Note: address above is anonymized

**Comment by xirixiz** [comment]
Valid point. I`ll update it in the upcoming weeks to make it more clear.
You could also create a PR if you like to.
