### ISSUE TITLE
foutmelding in logging meerdere integraties maar ook bij de afvalwijzer

### ISSUE THREAD

**Issue by nielswest65** [xirixiz/homeassistant-afvalwijzer#306]
### The problem

foutmelding in logging, p4 met hassio wordt afgesloten of addons uitgezet:

Logger: homeassistant.helpers.entity
Bron: helpers/entity.py:942
Eerst voorgekomen: 20:46:43 (14 gebeurtenissen)
Laatst gelogd: 20:59:43

Update for calendar.afvalwijzer fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/entities_calendar/calendar.py", line 176, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 184, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/entities_calendar/calendar.py", line 292, in update
    events.sort(key=lambda x: x.start )
TypeError: can't compare datetime.datetime to datetime.date

### Version of afvalwijzer integration having the issue?

2024.06.02

### Version of Home Assistant Core having the issue?

Core 2024.8.1 Supervisor 2024.08.0 Operating System 12.4 Frontend 20240809.0

### Anything in the logs that might be useful for us?

```txt
meerdere inegraties melden fouten op runner.py en entity.py ook daar issue aan het melden.
ik heb de core naar 13.0 gebracht, dat was een punt voor de foutmeldingen. hassio terug gezet naar 12... versie en db restore gedaan.
```

### Additional information

 xx

**Comment by gielk** [comment]
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:364
integration: Sensor (documentation, issues)
First occurred: 19:51:00 (1 occurrences)
Last logged: 19:51:00

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/afvalwijzer/sensor.py", line 68, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 92, in __init__
    waste_data_raw = ximmio.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 36, in get_waste_data_raw
    uniqueId = response["dataList"][0]["UniqueId"]
               ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Ik vermoed dat het issue verholpen is. Het lijkt erop dat de provider geen data door kon geven. Wanneer het nog wel een probleem is hoor ik het graag en duik ik er verder in.

**Comment by gielk** [comment]
Ik heb de provider veranderd naar Afvalwijzer dus de provider Meppel kan er uit.
