### ISSUE TITLE
Integration not working after update to 2024.9.1

### ISSUE THREAD

**Issue by QempZor** [xirixiz/homeassistant-afvalwijzer#314]
### The problem

All sensors are status Unknown after updating HA from 2024.9.0 to 2024.9.1

### Version of afvalwijzer integration having the issue?

HACS Release 2024.06.02

### Version of Home Assistant Core having the issue?

2024.9.1

### Anything in the logs that might be useful for us?

```txt
Error log:
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:361
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 20:08:01 (1 gebeurtenissen)
Laatst gelogd: 20:08:01

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/afvalwijzer/sensor.py", line 68, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 57, in __init__
    waste_data_raw = circulus.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/circulus.py", line 26, in get_waste_data_raw
    addresses = response["customData"]["addresses"]
                ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'customData'
```

**Comment by QempZor** [comment]
Spontaneously, today after a HA reboot (Already did that yesterday/2 days agao, a several times ofcourse) it's working again..

**Comment by xaetacore** [comment]
having the same issue right now.

i recently moved so i have to use burgerportaal now but now all of the sudden i get Platform error 'sensor' from integration 'burgerportaal' - Integration 'burgerportaal' not found.

I checked the logs and there's nothing useful.

any tips?
