### ISSUE TITLE
ACV seems to not work

### ISSUE THREAD

**Issue by joelhaasnoot** [xirixiz/homeassistant-afvalwijzer#323]
### The problem

The integration fails to setup, see logs below

Config is
```
sensor:
- platform: afvalwijzer
  provider: acv     
  postal_code: 6714KK
  street_number:  53
 ```

### Version of afvalwijzer integration having the issue?

2024.06.02

### Version of Home Assistant Core having the issue?

2024.10.3

### Anything in the logs that might be useful for us?

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: October 20, 2024 at 15:47:49 (1 occurrences)
Last logged: October 20, 2024 at 15:47:49

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/afvalwijzer/sensor.py", line 68, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 92, in __init__
    waste_data_raw = ximmio.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 36, in get_waste_data_raw
    uniqueId = response["dataList"][0]["UniqueId"]
               ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Could it be it's a new address? The address cannot be identified by your provider (XIMMIO):

```
-> python3 -m afvalwijzer.tests.test_module
Address not found!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/xirixiz/git/homeassistant-afvalwijzer/custom_components/afvalwijzer/tests/test_module.py", line 119, in <module>
    collector = MainCollector(
                ^^^^^^^^^^^^^^
  File "/home/xirixiz/git/homeassistant-afvalwijzer/custom_components/afvalwijzer/collector/main_collector.py", line 130, in __init__
    self._waste_data = WasteDataTransformer(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xirixiz/git/homeassistant-afvalwijzer/custom_components/afvalwijzer/common/waste_data_transformer.py", line 25, in __init__
    waste_data_raw.sort(key=lambda item: datetime.strptime(item["date"], "%Y-%m-%d"))
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sort'
```

**Comment by xirixiz** [comment]
Found the error. Fixed it. New release available at the end of this week.

**Comment by joelhaasnoot** [comment]
Thank you / bedankt! It's working now!
