### ISSUE TITLE
v4.4.2 - KeyError: 'ophaaldagen'

### ISSUE THREAD

**Issue by sanderjonkers** [xirixiz/homeassistant-afvalwijzer#77]
Just updated to version 4.4.2 through HACS, and I get the following in my HA log, and all trash sensors are gone.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 70, in async_setup_platform
    afvaldienst = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 47, in __init__
    self._trash_json = self.__get_json()
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 67, in __get_json
    json_data = (json_response['ophaaldagen']['data'] + json_response['ophaaldagenNext']['data'])
KeyError: 'ophaaldagen'

**Comment by xirixiz** [comment]
Did you read the readme? From now on you need an apikey or apitoken (in your config you nee to add ```api_token = ''```. I had to remove it from the source code from the provider. However no api keys are being provided by the provider....

L2 .... .gitignore ....

**Comment by xirixiz** [comment]
Oke, I'm almost done with a new and working component without using the API but with all the same functionality.
I`ll release it Tomorrow or the day after Tomorrow

**Comment by sanderjonkers** [comment]
> o

Nice! I will definately test it when released.
For now, I've rolled back to v4.4.0.
