### ISSUE TITLE
Error while setting up afvalwijzer platform for sensor

### ISSUE THREAD

**Issue by henkie86** [xirixiz/homeassistant-afvalwijzer#78]
Version 4.4.2

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 70, in async_setup_platform
    afvaldienst = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 47, in __init__
    self._trash_json = self.__get_json()
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 67, in __get_json
    json_data = (json_response['ophaaldagen']['data'] + json_response['ophaaldagenNext']['data'])
KeyError: 'ophaaldagen'

**Comment by xirixiz** [comment]
Does anyone read?? I'm not goin to answer this anymore, see the closed tickets or the readme for more info.

**Comment by xirixiz** [comment]
Oke, I'm almost done with a new and working component without using the API but with all the same functionality.
I`ll release it Tomorrow or the day after Tomorrow

**Comment by henkie86** [comment]
Hello, the sensor worked a couple of days, but after the last release i get the following error messages:

`Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/sensor.py:98
Integration: Sensor (documentation, issues)
First occurred: 4:39:46 PM (1 occurrences)
Last logged: 4:39:46 PM

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 98, in async_setup_platform
    afvaldienst = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/AfvaldienstScraper.py", line 50, in __init__
    self._trash_data, self._trash_data_custom = self.__get_data()
TypeError: cannot unpack non-iterable bool object`

**Comment by xirixiz** [comment]
Hi Henk, do you have a postcal code and housenumber for me?

**Comment by henkie86** [comment]
Hi Bram, excuse me
i see the problem, was still using the old sensor (with api key)
Changed it to scraper and works fine again.

Many thanks for the hard work en very nice integration you build
